export const paths = {
  home: '/',
  login: '/login',
  clips: '/clips',
  clip: (id: string) => `/clips/${id}`,
  add: '/add',
  recipes: '/recipes',
  recipeNew: '/recipes/new',
  recipe: (id: string) => `/recipes/${id}`,
  recipeEdit: (id: string) => `/recipes/${id}/edit`,
  recipeCompare: (id: string) => `/recipes/${id}/compare`,
  /** ノートの「メニュー」: お店のメニュー（確定して出しているレシピ）。下のタブの /menu（日々の記録）とは別 */
  shopMenu: '/shop-menu',
  /** ノートの「お店」: 行って気に入ったお店（Google マップのリンクで溜める） */
  places: '/places',
  place: (id: string) => `/places/${id}`,
  ask: '/ask',
  menu: '/menu',
  menuDay: (date: string) => `/menu/${date}`,
  menuStats: '/menu/stats',
  inbox: '/inbox',
  settings: '/settings',
  settingsProfile: '/settings/profile',
  settingsOutfit: '/settings/outfit',
  settingsFriends: '/settings/friends',
  settingsRules: '/settings/rules',
  settingsGenres: '/settings/genres',
  settingsPrices: '/settings/prices',
  settingsInstall: '/settings/install',
  devUi: '/dev/ui',
} as const
